### PR TITLE
Add Content-Range capability to the File getObject adapter.

### PR DESCRIPTION
**Pull request by yoohoomedia**
## What kind of change does this PR introduce?

Added Content-Range capability to the File adapter allowing for video streaming.

## What is the current behavior?

Storage module would not honour range requests when requesting video files from buckets files by clients using the public URL. Video players request video files with range values to improve loading performance. The File adapter would ignore these ranges and return the entire file, causing an excessive delay when attempting to play a large video file (ie: 1gb). 

## What is the new behavior?

File adapter checks for the existence of the Range header, then returns the appropriate chunk of the requested file. If the header is not present then it returns to the standard response containing the entire file.

### CODE REVIEW

**Review by fenos — APPROVED** [review]

**Comment by yoohoomedia** [comment]
I'm new to GitHub pull requests - I think I may have messed this request up.

**Comment by yoohoomedia** [comment]
Can someone please point me to documentation on how inter-repository forking/pull requests work or the process one should follow?
Thanks

**Comment by LautaroJayat** [comment]
@yoohoomedia
I think they expect something like the following:

1. fork the repo
2. create a new branch, in your case something like `feat/adding-content-range-capability-to-file-get-object-adapter`
3. develop & commit in there
4. push to your fork
5. create a PR

When creating a PR you will have to choose if you want to make that PR against your fork's main branch, or the supabase/storage-api repo main branch.

Anyways, I dont think you messed up this PR.

If you are worring about the failing test, I'm seeing the same error in other PRs and it seems to be something about a missing ENV value set in the secrets of the ci pipeline.

@fenos do you have any insight on this failing job?

**Comment by fenos** [comment]
Hello @yoohoomedia @LautaroJayat i definitely missed this PR! Apologies for the late reply!
I will get it reviewed and merged in the next couple of days

**Comment by fenos** [comment]
Thanks a lot @yoohoomedia!

**Pull request merged**
